### ISSUE TITLE
DAPRICOT scenario uses entire GPU memory

### ISSUE THREAD

**Issue by dxoigmn** [twosixlabs/armory#1122]
When I run the Armory 0.13.3's DAPRICOT scenario on the GPU within Docker:
```
armory run lib/armory/scenario_configs/dapricot_frcnn_masked_pgd.json --gpus 0
```
memory usage spikes to `11589MiB` right after the first execution of this line:
https://github.com/twosixlabs/armory/blob/c24928701b4ff6fc37cdb994ea784f9733a8e8da/armory/scenarios/dapricot_scenario.py#L168

This leaves no room on the GPU for our PyTorch model to execute and seems like a bug in the DAPRICOT loading code? Is this expected behavior? I see this same behavior when I execute the scenario with`--no-docker`.

**Comment by davidslater** [comment]
This, it turns out, was a problem with TFDS using TF2 gpu underneath the hood, which by default grabs all memory in the GPU. In the current develop branch (which will be released in the next month), we have limited GPU memory use by TF in dataset processing:
https://github.com/twosixlabs/armory/blob/develop/armory/__init__.py#L73-L87
