### ISSUE TITLE
Availability of scenario configs for Eval 4

### ISSUE THREAD

**Issue by anindya-paul** [twosixlabs/armory#1214]
Is it possible to share the scenario configuration that you used for eval 4 in object detection and tracking scenario generations for example weather settings, sensor transform, town map, and any other scenario parameter that you customized? We are thinking of re-creating and possibly augmenting the scenario datasets that you created, so obtaining the scenario configs will help us.

**Comment by lcadalzo** [comment]
@yusong-tan is there any context you can provide?

**Comment by yusong-tan** [comment]
@cbushomitre Can you share the information here so others can see?

**Comment by cbushomitre** [comment]
In order to make use of the configurations, a performer would need to have their own instance of CARLA to recreate the scenarios. The data needed to do this includes: custom maps and CARLA assets, a scenario file that defines the environment and routes the vehicles follow, and the sensors instantiated on the vehicle. If anyone needs access to these configurations, please reach out so we can grant access.
