### ISSUE TITLE
No module named armory.scenarios.main 

### ISSUE THREAD

**Issue by sfarkya** [twosixlabs/armory#1411]
Hello, 

I have been using this docker image and it was working fine earlier 
```

FROM twosixarmory/tf1:0.12.3
RUN pip install keras==2.3.0
RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y
RUN pip install git+https://github.com/qubvel/classification_models.git
RUN pip install keras==2.3.0 tqdm xxhash hickle requests wget googledrivedownloader colorama tabulate imageio opencv-
WORKDIR /workspace

```
but I tried it again and I am getting This error:
<img width="905" alt="Screen Shot 2022-04-15 at 12 33 54 PM" src="https://user-images.githubusercontent.com/6245078/163596608-69f9af0f-310c-4fb2-b1eb-1430887156b4.png">

Basically says that the docker container is unable to find: 
`/opt/conda/bin/python: No module named armory.scenarios.main `

Not sure if you have changed something on your side or am I missing something. Any insights you can provide on the issue? 
Thank you in advance!

**Comment by davidslater** [comment]
Armory has been restructured since 0.12.3, and uses a different entrypoint inside the container, which is what that error results from.

First, I would recommend updating your first line to:
```
FROM twosixarmory/tf1:0.14.4
```
and see if that fixes the issue.

Also, please note that we are deprecating the use of TF1, and so our new images starting in 0.15 will not have TF1. When those are released, you will need to use TF2 containers with tf1 compatibility mode to use tf1 code.
