### ISSUE TITLE
Add type checking to Writer classes?

### ISSUE THREAD

**Issue by lcadalzo** [twosixlabs/armory#1485]
Say a user adds a `hub.record("name", x_preprocessed)` , perhaps naively, to their code where `x_preprocessed` is a numpy array. This gets passed along to a `ResultsWriter` object, an element of `self.default_writers`, which then ultimately writes each  entire image array to output JSON.

To give an example of how unwieldy this gets: using the xView dataset with `--skip-attack --num-eval-batches 10`, this takes the config output length from ~100 lines (8KB) to ~ 6.5 million (230MB). 

Perhaps a related but separate aspect of this is whether we want `record()` to always push all records to all default writers.

**Comment by davidslater** [comment]
I added a numpy encoder for json so that it wouldn't error on numpy results coming out of metrics (which is much cleaner than doing all of the type casting to lists of floats, etc., than we currently do, and it also is easier to extend).

I think that maybe having a warning when the records are very large would be good.

**Comment by davidslater** [comment]
For the second question, I do think that it would be good for `record()` to be able to specific a writer. Something like:
```
    def record(self, name, result, writer=None):                                                      
        """                                                                              
        Push a record to the default writers                                             
        """
        if writer is not None:
            pass  # get writer and write
            return                                                                             
        if not self.default_writers:                                                     
            log.warning(f"No default writers to record {name}:{result} to")              
        for writer in self.default_writers:                                              
            writer.write((name, self.context["batch"], result)) 
```

**Comment by lcadalzo** [comment]
> For the second question, I do think that it would be good for `record()` to be able to specific a writer. Something like:
> 
> ```
>     def record(self, name, result, writer=None):                                                      
>         """                                                                              
>         Push a record to the default writers                                             
>         """
>         if writer is not None:
>             pass  # TODO: get writer and write
>             return                                                                             
>         if not self.default_writers:                                                     
>             log.warning(f"No default writers to record {name}:{result} to")              
>         for writer in self.default_writers:                                              
>             writer.write((name, self.context["batch"], result)) 
> ```

this is similar to what I added in #1486. Not only could/would we want a non-default writer to be used for a specific `record()` call, but we also could/would want the default writers to _not_ be used for said call (hence why I added a `use_default_writers` kwarg)

**Comment by davidslater** [comment]
This seems like something that should happen either in the `ResultsWriter` itself or the scenario's `evaluate / prepare_results`. The cleanest, in my mind, would be to add a "max_record_size" kwarg to the ResultsWriter (or even the base writer) that can be set to None / 0 / False for no max, and a positive int otherwise. When exceeding that value, we log a warning and probably drop the record or set to some sentinel value or descriptive value like `f"{size} exceeds max_record_size of {self.max_record_size}"`.

The challenge is how to do that without encoding it into JSON. `sys.getsizeof` can sort-of work, but gets tripped up by data structures. For instance:
```
>>> import numpy as np
>>> import sys
>>> a = np.random.random((960, 1280, 6))
>>> sys.getsizeof(a)
58982536
>>> sys.getsizeof("name")
53
>>> sys.getsizeof(None)
16
>>> sys.getsizeof(("name", None, a))
80
```

**Comment by lcadalzo** [comment]
I agree something along these lines makes sense. Helpful link on the issues with `sys.getsizeof()`: https://nedbatchelder.com/blog/202002/sysgetsizeof_is_not_what_you_want.html
