### ISSUE TITLE
`iscrowd` is wrong in the `val` and `dev` dataset

### ISSUE THREAD

**Issue by mzweilin** [twosixlabs/armory#1504]
I downloaded the train/val/dev datasets from 

```bash
wget https://armory-public-data.s3.us-east-2.amazonaws.com/carla/carla_od_train_val_2.0.0_dataset.tar.gz
wget https://armory-public-data.s3.us-east-2.amazonaws.com/carla/carla_od_dev_2.0.0.tar.gz
```

and I found that the `iscrowd` property is annotated in `val` and `dev`, not in `train`.

According to the COCO format definition at https://cocodataset.org/#format-data
> Crowd annotations (iscrowd=1) are used to label large groups of objects (e.g. a crowd of people).

there should not be `iscrowd=1`, because every individual object is annotated in Carla.

However, I found that some objects are annotated as `iscrowd=1` in `val` and `dev`. This could cause trouble because many existing COCO pipelines exclude `iscrowd=1` objects in annotation.

**Comment by davidslater** [comment]
@yusong-tan

**Comment by yusong-tan** [comment]
@mzweilin I'm not sure why `iscrowd` got dropped in annotation for the `train` data. This is why I manually set it to 0 [here](https://github.com/twosixlabs/armory/blob/9389c20a3c0150688a71e32309e1df0d00d3eb75/armory/data/carla_object_detection/carla_obj_det_train.py#L157) because that field was missing.

As for the comment about `iscrowd` should not be 1, this is how the CARLA tool from Intel annotates it, so I didn't change it when it's available.

**Comment by mzweilin** [comment]
> @mzweilin Is the fix simply post-processing our original annotations, or does the fix directly address how kwcoco works? A lot of these issues are the result of directly applying kwcoco, so I'm just wondering if they will crop up again in future annotations.

@yusong-tan  I just applied some ad-hoc fixes as post-processing on the original annotations.
