### ISSUE TITLE
Error running deepspeech ASR config, module missing | Fixed by installing deepspeech.pytorch locally instead of external repo

### ISSUE THREAD

**Issue by sonal-ssj** [twosixlabs/armory#1554]
Faced the following error running entailment config for deepspeech using official scenario config.

```
2022-06-07 08:34:57 19m53s INFO     armory.utils.external_repo:download_and_extract_repo:129 Downloading external repo: SeanNaren/deepspeech.pytorch@V3.0
2022-06-07 08:35:06 20m2s ERROR    armory.utils.external_repo:__exit__:36 deepspeech.pytorch is an external repo.
Please download from https://github.com/SeanNaren/deepspeech.pytorch@V3.0 and place on local environment PYTHONPATH
    OR place in experimental config `external_github_repo` field.
    See scenario_configs/librispeech_asr_snr_undefended.json for an example.
2022-06-07 08:35:06 20m2s ERROR    armory.scenarios.scenario:evaluate:397 Encountered error during scenario evaluation.

Traceback (most recent call last):

  File "/export/c11/sjoshi/miniconda3/envs/deepspeech_armory_june22/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': '\nMain script for running scenarios. Users will run a scenario by calling:\n    armory r...
           │         └ <code object <module> at 0x2adbcbafc870, file "/export/c11/sjoshi/miniconda3/envs/deepspeech_armory_june22/lib/python3.8/site...
           └ <function _run_code at 0x2adafd0df9d0>
  File "/export/c11/sjoshi/miniconda3/envs/deepspeech_armory_june22/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': '\nMain script for running scenarios. Users will run a scenario by calling:\n    armory r...
         └ <code object <module> at 0x2adbcbafc870, file "/export/c11/sjoshi/miniconda3/envs/deepspeech_armory_june22/lib/python3.8/site...
  File "/export/c11/sjoshi/miniconda3/envs/deepspeech_armory_june22/lib/python3.8/site-packages/armory/scenarios/main.py", line 228, in <module>
    run_config(
    └ <function run_config at 0x2adbcce3de50>
  File "/export/c11/sjoshi/miniconda3/envs/deepspeech_armory_june22/lib/python3.8/site-packages/armory/scenarios/main.py", line 144, in run_config
    scenario.evaluate()
    │        └ <function Scenario.evaluate at 0x2adbcdcf4b80>
    └ <armory.scenarios.audio_asr.AutomaticSpeechRecognition object at 0x2adafda63520>
> File "/export/c11/sjoshi/miniconda3/envs/deepspeech_armory_june22/lib/python3.8/site-packages/armory/scenarios/scenario.py", line 388, in evaluate
    self._evaluate()
    │    └ <function Scenario._evaluate at 0x2adbcdcf4af0>
    └ <armory.scenarios.audio_asr.AutomaticSpeechRecognition object at 0x2adafda63520>
  File "/export/c11/sjoshi/miniconda3/envs/deepspeech_armory_june22/lib/python3.8/site-packages/armory/scenarios/scenario.py", line 377, in _evaluate
    self.load()
    │    └ <function Scenario.load at 0x2adbcdcf4670>
    └ <armory.scenarios.audio_asr.AutomaticSpeechRecognition object at 0x2adafda63520>
  File "/export/c11/sjoshi/miniconda3/envs/deepspeech_armory_june22/lib/python3.8/site-packages/armory/scenarios/scenario.py", line 271, in load
    self.load_model()
    │    └ <function AutomaticSpeechRecognition.load_model at 0x2adbcdcf4e50>
    └ <armory.scenarios.audio_asr.AutomaticSpeechRecognition object at 0x2adafda63520>
  File "/export/c11/sjoshi/miniconda3/envs/deepspeech_armory_june22/lib/python3.8/site-packages/armory/scenarios/audio_asr.py", line 91, in load_model
    super().load_model(defended=defended)
                                └ True
  File "/export/c11/sjoshi/miniconda3/envs/deepspeech_armory_june22/lib/python3.8/site-packages/armory/scenarios/scenario.py", line 109, in load_model
    model, _ = config_loading.load_model(model_config)
               │              │          └ {'fit': False, 'fit_kwargs': {'nb_epochs': 20000}, 'model_kwargs': {}, 'module': 'armory.baseline_models.pytorch.deep_speech'...
               │              └ <function load_model at 0x2adbcce3d8b0>
               └ <module 'armory.utils.config_loading' from '/export/c11/sjoshi/miniconda3/envs/deepspeech_armory_june22/lib/python3.8/site-pa...
  File "/export/c11/sjoshi/miniconda3/envs/deepspeech_armory_june22/lib/python3.8/site-packages/armory/utils/config_loading.py", line 90, in load_model
    model_module = import_module(model_config["module"])
                   │             └ {'fit': False, 'fit_kwargs': {'nb_epochs': 20000}, 'model_kwargs': {}, 'module': 'armory.baseline_models.pytorch.deep_speech'...
                   └ <function import_module at 0x2adafd068790>
  File "/export/c11/sjoshi/miniconda3/envs/deepspeech_armory_june22/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'armory.baseline_models.pytorch.deep_speech'
           │          └ <function _gcd_import at 0x2adafcf5c430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/export/c11/sjoshi/miniconda3/envs/deepspeech_armory_june22/lib/python3.8/site-packages/armory/baseline_models/pytorch/deep_speech.py", line 18, in <module>
    from deepspeech_pytorch.model import DeepSpeech  # noqa: F401

  File "/export/b15/sjoshi/armory/.armory/tmp/2022-06-07T121500.479684/external/deepspeech.pytorch/deepspeech_pytorch/model.py", line 15, in <module>
    from deepspeech_pytorch.validation import CharErrorRate, WordErrorRate

  File "/export/b15/sjoshi/armory/.armory/tmp/2022-06-07T121500.479684/external/deepspeech.pytorch/deepspeech_pytorch/validation.py", line 9, in <module>
    from pytorch_lightning.metrics import Metric

ModuleNotFoundError: No module named 'pytorch_lightning.metrics'
```

Solved it by setting `external_github_repo` to `null` in https://github.com/twosixlabs/armory/blob/master/scenario_configs/eval5/asr_librispeech/entailment.json#L76  and installing deepspeech locally

**Comment by lcadalzo** [comment]
Hi Sonal, thanks for reporting this. The presence of 
```
2022-06-07 08:35:06 20m2s ERROR    armory.utils.external_repo:__exit__:36 deepspeech.pytorch is an external repo.
Please download from https://github.com/SeanNaren/deepspeech.pytorch@V3.0 and place on local environment PYTHONPATH
    OR place in experimental config `external_github_repo` field.
```

in your logs (which is logged [here](https://github.com/twosixlabs/armory/blob/master/armory/utils/external_repo.py#L36)) seems to indicate something went wrong with the download of `SeanNaren/deepspeech.pytorch@V3.0`. Is it possible there was some sort of connection issue with your local machine? Are you able to reproduce the result consistently?

I am unable to reproduce the error, and when I set a `breakpoint()` in the code when running Armory with the `--interactive` flag, I see I'm able to import those modules:
```

> /workspace/armory/scenarios/scenario.py(317)run_attack()
(Pdb) import pytorch_lightning
(Pdb) from pytorch_lightning.metrics import Metric
```

**Comment by sonal-ssj** [comment]
Thanks for your reply. I am not sure why it doesn't download the external repo. The logs do not indicate any https error or download issue.
```
2022-06-08 01:29:46 47s INFO     armory.utils.external_repo:download_and_extract_repo:129 Downloading external repo: SeanNaren/deepspeech.pytorch@V3.0
2022-06-08 01:29:58 59s ERROR    armory.utils.external_repo:__exit__:36 deepspeech.pytorch is an external repo.
Please download from https://github.com/SeanNaren/deepspeech.pytorch@V3.0 and place on local environment PYTHONPATH
    OR place in experimental config `external_github_repo` field.
    See scenario_configs/librispeech_asr_snr_undefended.json for an example.
2022-06-08 01:29:58 59s ERROR    armory.scenarios.scenario:evaluate:397 Encountered error during scenario evaluation.
```
I am able to reproduce the error if I add the external repo. No clue why it is happening though!

**Comment by lcadalzo** [comment]
Here is a minimal code snippet that should hopefully shed more light on what may be going wrong:
```
from armory.utils.external_repo import download_and_extract_repo
download_and_extract_repo("SeanNaren/deepspeech.pytorch@V3.0")
```

Note that you'll need to run this inside an Armory container. To launch one, run the config with the `--interactive` flag. When I run the above 2 lines of code, I see the following logs:
```
/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.github.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'codeload.github.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2022-06-08 15:47:01  0s INFO     armory.utils.external_repo:download_and_extract_repo:129 Downloading external repo: SeanNaren/deepspeech.pytorch@V3.0

```
(the warnings above appear because my `~/.armory/config.json`, where global Armory settings live, sets `"verify_ssl"` to `false`)

You could try swapping in a different repo to see if the issue is specific to deepspeech

**Comment by sonal-ssj** [comment]
Thanks for the suggestion. However, I would not be able to run the docker as our grid does not support it.  (We usually run our systems on grid and then make docker on our local machine). Is there any other way to reproduce the error inside python env without using docker?

**Comment by lcadalzo** [comment]
are you running with the `--no-docker` flag then? If so, you should be able to run those 2 lines of code in whatever environment from which you're running Armory. Armory is the only dependency needed to run those 2 lines

**Comment by sonal-ssj** [comment]
Yes, I am running with  `--no-docker` flag. I ran the snippet in the environment and it seems its a path permissions issue

```
(deepspeech_armory_june22) Wed Jun 08 12:57:41 b07:v2$ python
>>> from armory.utils.external_repo import download_and_extract_repo
>>> download_and_extract_repo("SeanNaren/deepspeech.pytorch@V3.0")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export/c11/sjoshi/miniconda3/envs/icefall_armory_june22/lib/python3.8/site-packages/armory/utils/external_repo.py", line 108, in download_and_extract_repo
    os.makedirs(external_repo_dir, exist_ok=True)
  File "/export/c11/sjoshi/miniconda3/envs/icefall_armory_june22/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/export/c11/sjoshi/miniconda3/envs/icefall_armory_june22/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/export/c11/sjoshi/miniconda3/envs/icefall_armory_june22/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/armory'
```

I went back to check if my armory paths are configured right and they seem to be ok. I have write permissions to all the set paths here

 ```
   dataset_dir:     /export/b15/sjoshi/armory/.armory/datasets
    local_git_dir:   /home/sjoshi/.armory/git
    saved_model_dir: /export/b15/sjoshi/armory/.armory/saved_models
    tmp_dir:         /export/b15/sjoshi/armory/.armory/tmp
    output_dir:      /export/b15/sjoshi/armory/.armory/outputs
```
Is there some armory config I am missing that is pointing to my root directory?

**Comment by lcadalzo** [comment]
Hi Sonal, I've taken a closer look at this. I'll include more detail below, but are you able to write to the following directory: `~/.armory/tmp`? Long story short, I believe that's where Armory is trying to write the repo contents. I think we could add an update to Armory that instead writes to the `tmp_dir` specified in the armory config i.e. `/export/b15/sjoshi/armory/.armory/tmp` in your case, rather than always `~/.armory/tmp`.


---------------------
After looking a bit closer, that 2-line snippet isn't representative of what's going on since it doesn't pass a `external_repo_dir` kwarg to the `download_and_extract_repo()` call. The 2-line snippet consequently reaches [this](https://github.com/twosixlabs/armory/blob/v0.15.3/armory/utils/external_repo.py#L105-L106) conditional block, which is not the case when running the config.

Instead, when running the config, Armory passes in the [scenario_tmp_dir](https://github.com/twosixlabs/armory/blob/v0.15.3/armory/scenarios/main.py#L54) variable as the `external_repo_dir`. So the question is then why you're having issues writing to `scenario_tmp_dir`, which is defined [here](https://github.com/twosixlabs/armory/blob/v0.15.3/armory/scenarios/main.py#L45) as `runtime_paths.tmp_dir`. If we look [here](https://github.com/twosixlabs/armory/blob/v0.15.3/armory/paths.py#L42) at where `runtime_paths` is defined, given that the `NO_DOCKER` variable should be `True` in your case, we see that `tmp_dir` is defined [here](https://github.com/twosixlabs/armory/blob/v0.15.3/armory/paths.py#L75) to be inside `self.armory_dir` which is defined [here](https://github.com/twosixlabs/armory/blob/v0.15.3/armory/paths.py#L69) as `os.path.join(os.path.expanduser("~"), ".armory")`.

All that's to say, the directory it's having trouble writing to should be 

```
os.path.join(os.path.expanduser("~"), ".armory", "tmp", config["eval_id"], "external")
```

In my case, this amounts to the following:
```
>>> config_eval_id = "2022-06-10T170948.859080"
>>> os.path.join(os.path.expanduser("~"), ".armory", "tmp", config_eval_id, "external")
'/home/lucas/.armory/tmp/2022-06-10T170948.859080/external'
```

I think the relevant piece here is `/home/lucas/.armory/tmp`

**Comment by sonal-ssj** [comment]
Thanks for looking into this. I am able to write to both the directories you mentioned. I think the directory that the issue is occurring is `/armory'` as in `PermissionError: [Errno 13] Permission denied: '/armory'` and not `/.armory`. Any chance there is a typo (missing `.`) somewhere?

**Comment by lcadalzo** [comment]
You only see `PermissionError: [Errno 13] Permission denied: '/armory'` when running the 2-line snippet, correct? For the reasons described in my previous message, that snippet isn't indicative of what's occurring when you run the config, and I retract my suggestion to use it for debugging. Since you're retrieving `runtime_paths` outside the context of runtime, the `NO_DOCKER` variable doesn't get the chance to be properly set to `True` (note that I get the same `PermissionError: [Errno 13] Permission denied: '/armory'` when running those 2 lines). In short, I led us down the wrong debugging path, my apologies.

I think the issue is simpler, actually, and is related to your environment. I notice that the import of `deepspeech_pytorch` doesn't err, but rather the underlying `pytorch_lightning`. So I think the external repo is being downloaded fine, but it appears your environment isn't set up with `pytorch_lightning`. Have you followed [these](https://github.com/twosixlabs/armory/blob/v0.15.3/host-requirements.txt#L53-L61) instructions? You should be able to open an interactive Python shell and import that library without error:
```
>>> import pytorch_lightning
>>>
```
