### ISSUE TITLE
Error running Carla multimodal object detection with JPEG compression

### ISSUE THREAD

**Issue by iamwyh2019** [twosixlabs/armory#1924]
I am using the baseline undefended model for Carla multimodal object detection ([here](https://github.com/twosixlabs/armory/blob/master/armory/baseline_models/pytorch/carla_multimodality_object_detection_frcnn.py)) with JPEG compression as defense. We are using the same scenario config [(here)](https://github.com/twosixlabs/armory/blob/master/scenario_configs/eval5/carla_object_detection/carla_obj_det_multimodal_adversarialpatch_undefended.json) and added the "defense" key:

`"defense": {
        "kwargs": {
            "apply_fit": false,
            "apply_predict": true,
            "clip_values": [
                0.0,
                1.0
            ],
            "quality": 50
        },
        "module": "art.defences.preprocessor",
        "name": "JpegCompression",
        "type": "Preprocessor"
    },`

We get `NotImplementedError: Combination of inputs and preprocessing not supported.`

A screenshot of the error is here:
<img width="1467" alt="image" src="https://user-images.githubusercontent.com/51950361/236074467-674973a2-5cbe-4179-b1bc-0829414abe66.png">

We tried to leave the `defense` part null, and pass a `JPEGCompression` instance to `preprocessing_defenses` in the PyTorchFasterRCNN, but got the same result.

Thank you.

**Comment by swsuggs** [comment]
This is happening because the JpegCompression defense is not implemented in PyTorch and so is not fully differentiable.  It can not be used with the CARLAAdversarialPatchPyTorch attack.  You can try using the CARLADapricotPatch attack as in this [config](https://github.com/twosixlabs/armory/blob/master/scenario_configs/eval6/carla_overhead_object_detection/carla_obj_det_multimodal_dpatch_undefended.json), which does not require a fully differentiable defense; be aware that it is considerably slower.
