### ISSUE TITLE
KeyError: 'dataset_name'

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [twosixlabs/armory#453]
I was trying to download the resources required to run `armory-example/official_scenario_configs/mnist_baseline.json` but I get the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/armory/data/datasets.py", line 487, in download_all
    for dataset in config["scenario"][scenario]["dataset_name"]:
KeyError: 'dataset_name'
```
It seems that the format used in the parser does not match the scenario examples.

Details:

```
leclerc@deep-gpu-10:~$ armory --version
0.6.0
leclerc@deep-gpu-10:~/armory-example$ git rev-parse HEAD
83030b9abe498edb2b0b1e83010c501efb43fcc1
```

The command I was running is:

`armory download armory-example/official_scenario_configs/mnist_baseline.json`

**Comment by ng390** [comment]
Sorry for the confusion in the documentation: the armory download command takes a download config file like scenarios-set1.json as an input, i.e.

`armory download armory-example/scenarios-set1.json`

It is meant as a convenience to download all of the datasets/docker containers (note that it will take some time to run)--it is not a requirement to run it. In the next patch release we will enhance the error logging if it receives a .json file of a scenario rather than a download config.

If you call
`armory run armory-example/official_scenario_configs/mnist_baseline.json`
the scenario should run and download the needed files (though again the first time there may be overhead to pull the Docker container).

**Comment by seanpmorgan** [comment]
Yeah documentation could be improved there. Thanks for reporting. I do think it's intuitive for users to point `armory download` at a run config and have it download that data. We'll discuss if that's a possibility but don't want to overload the functionality of the call either.

**Comment by GuillaumeLeclerc** [comment]
Got it. It's working!
