### ISSUE TITLE
Example for Plugging a pre-trained TF model into Armory for evaluation

### ISSUE THREAD

**Issue by superctj** [twosixlabs/armory#566]
I am attempting to use Armory to evaluate a pre-trained Tensorflow model in this [repo](https://github.com/MadryLab/cifar10_challenge). I wrote the wrapper code and the config file similar to those posted in Armory repo and Armory-Example repo. However, I keep having errors when running the code. Could you take a look at this issue? I attach [a link to my code](https://github.com/superctj/cifar10_challenge/tree/master/armory) and the stack trace for your reference.

<img width="555" alt="Screen Shot 2020-05-18 at 11 42 16 AM" src="https://user-images.githubusercontent.com/33765174/82250613-c8c7f080-9919-11ea-89cc-96f4370a21cf.png">

<img width="557" alt="Screen Shot 2020-05-18 at 11 43 16 AM" src="https://user-images.githubusercontent.com/33765174/82250625-cd8ca480-9919-11ea-8018-556206266dbc.png">

**Comment by seanpmorgan** [comment]
Hi @superctj so looking at the code, I believe the issue is that you've created new placeholders that are given to the wrapper:
https://github.com/superctj/cifar10_challenge/blob/master/armory/arch/wrapper.py#L26-L28

But these are not the same placeholders that are part of your model's graph:
https://github.com/superctj/cifar10_challenge/blob/master/armory/arch/model.py#L31-L37

You'll need to retrieve the models input tensors and use those as arguments to the wrapper. Something similar to:
```
input_ph = tf.get_default_graph().get_tensor_by_name("inputs/Placeholder:0")
```

But you may need to inspect your models graph. Alternatively since this Model is a python object I think you could just use `model.x_input`

**Comment by superctj** [comment]
Thank you for your quick response! I tried the alternative but it raised a new error.
<img width="551" alt="Screen Shot 2020-05-18 at 5 32 08 PM" src="https://user-images.githubusercontent.com/33765174/82261683-80b2c900-992d-11ea-8d82-1f67e50808fb.png">

By the way, do you have a workable TF wrapper code I can refer to?

**Comment by superctj** [comment]
I think I figure it out. In the model.py, `self.y_input = tf.placeholder(tf.int64, shape=None)`, so the tensor does not have the shape attribute. But if I wrap it as `self.y_input = tf.placeholder(tf.int64, shape=[None])`, it can safely pass the shape check.

This issue is resolved. Thank you for your help @seanpmorgan. If it is okay, I am very happy to contribute my code as an example for future Armory+TF users.

**Comment by seanpmorgan** [comment]
> I think I figure it out. In the model.py, `self.y_input = tf.placeholder(tf.int64, shape=None)`, so the tensor does not have the shape attribute. But if I wrap it as `self.y_input = tf.placeholder(tf.int64, shape=[None])`, it can safely pass the shape check.
> 
> This issue is resolved. Thank you for your help @seanpmorgan. If it is okay, I am very happy to contribute my code as an example for future Armory+TF users.

An example would be great... thanks! Probably best to add it to the [armory-example repository](https://github.com/twosixlabs/armory-example)
