### ISSUE TITLE
Enable tar files passed in as model_weights to be automatically expanded

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#921]

**Comment by adamj26** [comment]
To confirm, is what's requested here the ability to give a tar file as the `model_weights` in the scenario JSON and have armory unpack the tarfile (in place in .armory/datasets?) as part of the model loading process?

**Comment by davidslater** [comment]
Yes, ideally it would unpack the weights file in place (probably in .armory/saved_models/), and then return the full directory path. We would probably want to check that the files in the tarfile are extracted into a subdir (don't modify files outside of that subdir). For AWS, we might need to unpack this in a temp directory?

**Comment by adamj26** [comment]
Gotcha; thanks for the clarifications. If the tarball doesn't unpack into a subdir, should we create a subdir and attempt to corral the files into it or just error out?

This'll need dedicated handling code in AWS, since it happens before container startup, but we're already planning to redo how we handle `saved_models` and `datasets` in AWS in general, so we should be able to roll adding support for this into that work

**Comment by davidslater** [comment]
I would just error out or skip those files and log a warning. Erroring is probably easier.
